name: chat_app2_lite
description: "Sathi Lite - Simplified chat app without profile customization."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # use a proper Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  google_fonts: ^6.1.0

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  flutter_markdown: ^0.6.18

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^19.4.1

  # Background execution and lifecycle management
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# CLI tools (not runtime)
dependency_overrides:
  flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/male.jpg
    - assets/female.jpg
    - assets/splscreen.png
    - assets/bg_image.png
    - assets/bg_light.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21